# .circleci/config.yml
version: 2.1
executors:
  ios-executor:
    docker:
      - image: circleci/apple:latest
    working_directory: ~/project

jobs:
  build:
    executor: ios-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Build iOS Project
          command: |
            xcodebuild -workspace WanderView.xcworkspace -scheme WanderView -destination 'platform=iOS Simulator,name=iPhone 12' build

  clean:
    executor: ios-executor
    steps:
      - checkout
      - run:
          name: Clean Project
          command: |
            xcodebuild clean -workspace WanderView.xcworkspace -scheme WanderView

  run_tests:
    executor: ios-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Run Unit Tests
          command: |
            xcodebuild -workspace WanderView.xcworkspace -scheme WanderView -destination 'platform=iOS Simulator,name=iPhone 12' test

workflows:
  version: 2
  build-clean-test:
    jobs:
      - build
      - clean
      - run_tests:
          requires:
            - build
            - clean



