# .circleci/config.yml
version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run: pod install

      # Build and test your iOS app
      - run:
          name: Build and Test
          command: |
            xcodebuild clean build -scheme WanderView -workspace WanderView.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11'
            xcodebuild test -scheme WanderView -workspace WanderView.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11'

workflows:
  build-test:
    jobs:
      - build-and-test


