version: 2.1
jobs:
  build:
    macos:
      xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Build iOS Project
          command: |
            xcodebuild -workspace WanderView.xcworkspace -scheme WanderView -destination 'platform=iOS Simulator,name=iPhone 12' build

  clean:
    macos:
      xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: Clean Project
          command: |
            xcodebuild clean -workspace WanderView.xcworkspace -scheme WanderView

  run_tests:
    macos:
      xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Run Unit Tests
          command: |
            xcodebuild -workspace WanderView.xcworkspace -scheme WanderView -destination 'platform=iOS Simulator,name=iPhone 12' test

workflows:
  version: 2
  build-clean-test:
    jobs:
      - build
      - clean
      - run_tests:
          requires:
            - build
            - clean
