machine:
  xcode:
    version: "15.3.1"

checkout:
  post:
    - git submodule update --init --recursive

dependencies:
  pre:
   - brew update || brew update
    - brew outdated xctool || brew upgrade xctool

test:
  override:
    - rake test:ios
    - rake test:osx
    - rake test:xctool_ios
