fastlane_version "2.0"

default_platform :ios

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "WanderViewTests",
      clean: true,
      devices: ["iPhone 12"],
      code_coverage: true
    )
  end
end
